const pieces = [["Aragon", "F Major", "Albeniz", 5, 5, "Contemporary", [], ["Suite Espagnola", 6], 1],
["Asturias", "g minor", "Albeniz", 6, 5, "Contemporary", [], ["Suite Espagnola", 5], 1],
["Cadiz", "Db Major", "Albeniz", 5, 5, "Contemporary", [], ["Suite Espagnola", 4], 1],
["Castilla", "F# Major", "Albeniz", 3, 5, "Contemporary", ["stamina"], ["Suite Espagnola", 7], 1],
["Catalunya", "g minor", "Albeniz", 3, 5, "Contemporary", [], ["Suite Espagnola", 2], 1],
["Cuba", "Eb Major", "Albeniz", 6, 5, "Contemporary", [], ["Suite Espagnola", 8], 1],
["Granada", "F Major", "Albeniz", 6, 5, "Contemporary", [], ["Suite Espagnola", 1], 1],
["Sevilla", "G Major", "Albeniz", 5, 5, "Contemporary", [], ["Suite Espagnola", 3], 1],
["Concerto No 7 BWV 1058 Mvt 1", "g minor", "Bach", 4, 5, "Baroque", [], "", 1],
["Invention No 8", "F Major", "Bach", 1, 5, "Baroque", [], "", 1],
["Prelude and Fugue BWV 881", "f minor", "Bach", 6, 5, "Baroque", [], "", 1],
["Islamey", "Db Major", "Balakirev", 8, 3, "Romantic", [], "", 1],
["Hungarian Pictures", "f# minor", "Bartok", 11, 2, "Contemporary", ["impressions"], "Hungarian Pictures", 1],
["Romanian Folk Dances", "a minor", "Bartok", 6, 4, "Contemporary", [], "", 1],
["Piano Concerto No 1 Mvt 1", "C Major", "Beethoven", 19, 4, "Classical", [], "Piano Concerto No 1", 1],
["Piano Concerto No 1 Mvt 2", "Ab Major", "Beethoven", 11, 3, "Classical", [], "Piano Concerto No 1", 1],
["Piano Concerto No 1 Mvt 3", "C Major", "Beethoven", 9, 4, "Classical", [], "Piano Concerto No 1", 1],
["Piano Concerto No 3 Mvt 1", "c minor", "Beethoven", 17, 4, "Classical", [], "Piano Concerto No 3", 1],
["Piano Concerto No 3 Mvt 2", "E Major", "Beethoven", 11, 4, "Classical", [], "Piano Concerto No 3", 1],
["Piano Concerto No 3 Mvt 3", "c minor", "Beethoven", 9, 4, "Classical", [], "Piano Concerto No 3", 1],
["Piano Concerto No 4 Mvt 1", "G Major", "Beethoven", 20, 3, "Classical", [], "Piano Concerto No 4", 1],
["Piano Concerto No 4 Mvt 2", "e minor", "Beethoven", 6, 4, "Classical", [], "Piano Concerto No 4", 1],
["Piano Concerto No 4 Mvt 3", "G Major", "Beethoven", 10, 3, "Classical", ["stamina"], "Piano Concerto No 4", 1],
["Piano Concerto No 5 Mvt 1", "Eb Major", "Beethoven", 21, 3, "Classical", [], "Piano Concerto No 5", 1],
["Piano Concerto No 5 Mvt 2", "B Major", "Beethoven", 9, 3, "Classical", ["uplifting", "tender"], "Piano Concerto No 5", 1],
["Piano Concerto No 5 Mvt 3", "Eb Major", "Beethoven", 12, 4, "Classical", [], "Piano Concerto No 5", 1],
["Rage over a Lost Penny", "G Major", "Beethoven", 6, 4, "Classical", ["stamina"], "", 1],
["Sonata No 1 Mvt 14", "f minor", "Beethoven", 7, 3, "Classical", ["stamina"], "Early Sonatas", 1],
["Sonata No 2 Mvt 13", "A Major", "Beethoven", 8, 4, "Classical", [], "Early Sonatas", 1],
["Sonata No 3 Mvt 1", "C Major", "Beethoven", 10, 4, "Classical", [], "Early Sonatas", 1],
["Sonata No 4 Mvt 134", "Eb Major", "Beethoven", 18, 4, "Classical", [], "Early Sonatas", 1],
["Sonata No 5 Mvt 1", "c minor", "Beethoven", 4, 5, "Classical", [], "Early Sonatas", 1],
["Sonata No 6 Mvt 13", "F Major", "Beethoven", 6, 4, "Classical", [], "Early Sonatas", 1],
["Sonata No 7 Mvt 1", "D Major", "Beethoven", 7, 3, "Classical", ["stamina"], "Early Sonatas", 1],
["Sonata No 8", "c minor", "Beethoven", 20, 3, "Classical", [], "Early Sonatas", 1],
["Sonata No 9 Mvt 1", "E Major", "Beethoven", 5, 4, "Classical", ["stamina"], "Early Sonatas", 1],
["Sonata No 10 Mvt 12", "G Major", "Beethoven", 11, 4, "Classical", [], "Early Sonatas", 1],
["Sonata No 11 Mvt 14", "Bb Major", "Beethoven", 15, 3, "Classical", [], "Early Sonatas", 1],
["Sonata No 12 Mvt 3", "ab minor", "Beethoven", 6, 4, "Classical", ["dark"], "Early Sonatas", 1],
["Sonata No 13", "Eb Major", "Beethoven", 16, 4, "Classical", [], "Early Sonatas", 1],
["Sonata No 14", "c# minor", "Beethoven", 15, 3, "Classical", ["dark"], "Early Sonatas", 1],
["Sonata No 15 Mvt 134", "D Major", "Beethoven", 19, 3, "Classical", ["sleepy"], "Early Sonatas", 1],
["Sonata No 16 Mvt 1", "G Major", "Beethoven", 7, 5, "Classical", [], "Early Sonatas", 1],
["Sonata No 17", "d minor", "Beethoven", 23, 3, "Classical", ["dark"], "Middle Sonatas", 1],
["Sonata No 18 Mvt 14", "Eb Major", "Beethoven", 10, 4, "Classical", ["stamina"], "Middle Sonatas", 1],
["Sonata No 19", "g minor", "Beethoven", 9, 5, "Classical", [], "Early Sonatas", 1],
["Sonata No 20", "G Major", "Beethoven", 7, 5, "Classical", [], "Early Sonatas", 1],
["Sonata No 21 Mvt 13", "C Major", "Beethoven", 18, 3, "Classical", [], "Middle Sonatas", 1],
["Sonata No 22", "F Major", "Beethoven", 12, 4, "Classical", [], "Middle Sonatas", 1],
["Sonata No 23", "f minor", "Beethoven", 26, 4, "Classical", ["legendary"], "Middle Sonatas", 1],
["Sonata No 24", "F# Major", "Beethoven", 10, 4, "Classical", [], "Middle Sonatas", 1],
["Sonata No 25", "G Major", "Beethoven", 12, 4, "Classical", [], "Middle Sonatas", 1],
["Sonata No 26", "Eb Major", "Beethoven", 19, 4, "Classical", [], "Middle Sonatas", 1],
["Sonata No 27", "e minor", "Beethoven", 14, 3, "Classical", [], "Middle Sonatas", 1],
["Sonata No 28", "A Major", "Beethoven", 21, 2, "Romantic", ["legendary", "uplifting"], "Late Sonatas", 1],
["Sonata No 29", "Bb Major", "Beethoven", 42, 2, "Romantic", ["legendary"], "Late Sonatas", 1],
["Sonata No 30", "E Major", "Beethoven", 19, 2, "Romantic", ["legendary"], "Late Sonatas", 1],
["Sonata No 31", "Ab Major", "Beethoven", 20, 2, "Romantic", ["legendary", "tender"], "Late Sonatas", 1],
["Sonata No 32", "c minor", "Beethoven", 30, 2, "Romantic", ["legendary", "experimental"], "Late Sonatas", 1],
["Symphony No 3 Mvt 1", "Eb Major", "Beethoven", 15, 4, "Classical", [], "", 1],
["Symphony No 5 Mvt 1", "c minor", "Beethoven", 8, 4, "Classical", [], "Symphony No 5", 1],
["Symphony No 5 Mvt 2", "Ab Major", "Beethoven", 10, 4, "Classical", ["legendary", "uplifting"], "Symphony No 5", 1],
["Symphony No 5 Mvt 3", "c minor", "Beethoven", 6, 4, "Classical", [], "Symphony No 5", 1],
["Symphony No 5 Mvt 4", "C Major", "Beethoven", 9, 4, "Classical", [], "Symphony No 5", 1],
["Symphony No 7 Mvt 1", "A Major", "Beethoven", 13, 4, "Classical", [], "Symphony No 7", 1],
["Symphony No 7 Mvt 2", "a minor", "Beethoven", 9, 4, "Classical", [], "Symphony No 7", 1],
["Symphony No 7 Mvt 3", "F Major", "Beethoven", 9, 4, "Classical", ["stamina"], "Symphony No 7", 1],
["Symphony No 7 Mvt 4", "A Major", "Beethoven", 7, 4, "Classical", ["stamina"], "Symphony No 7", 1],
["Symphony No 9 Mvt 1", "d minor", "Beethoven", 18, 5, "Classical", [], "Symphony No 9", 1],
["Symphony No 9 Mvt 2", "D Major", "Beethoven", 12, 5, "Classical", [], "Symphony No 9", 1],
["Symphony No 9 Mvt 3", "Bb Major", "Beethoven", 18, 5, "Classical", [], "Symphony No 9", 1],
["Symphony No 9 Mvt 4", "D Major", "Beethoven", 8, 5, "Classical", ["troll"], "Symphony No 9", 1],
["Carmen Prelude", "A Major", "Bizet", 3, 4, "Romantic", [], "", 1],
["Habanera", "D Major", "Bizet", 3, 4, "Romantic", [], "", 1],
["Toreador Song", "F Major", "Bizet", 3, 4, "Romantic", [], "", 1],
["Ballade Op 118 No 3", "g minor", "Brahms", 4, 5, "Romantic", [], ["Six Piano Pieces Op 118", 3], 1],
["Capriccio Op 76 No 1", "f# minor", "Brahms", 4, 4, "Romantic", [""], "", 1],
["Capriccio Op 76 No 2", "b minor", "Brahms", 4, 4, "Romantic", [""], "", 1],
["Capriccio Op 116 No 3", "g minor", "Brahms", 3, 4, "Romantic", ["stamina"], "", 1],
["Hungarian Dance No 1", "g minor", "Brahms", 3, 4, "Romantic", [], "", 1],
["Hungarian Dance No 3", "F Major", "Brahms", 3, 4, "Romantic", [], "", 1],
["Hungarian Dance No 4", "f# minor", "Brahms", 5, 4, "Romantic", [], "", 1],
["Hungarian Dance No 5", "g minor", "Brahms", 4, 4, "Romantic", [], "", 1],
["Hungarian Dance No 6", "D Major", "Brahms", 4, 4, "Romantic", [], "", 1],
["Hungarian Dance No 7", "F Major", "Brahms", 2, 4, "Romantic", [], "", 1],
["Hungarian Dance No 17", "f# minor", "Brahms", 3, 4, "Romantic", [], "", 1],
["Intermezzo Op 117 No 1", "Eb Major", "Brahms", 5, 4, "Romantic", ["tender", "sleepy"], "", 1],
["Intermezzo Op 118 No 1", "a minor", "Brahms", 2, 4, "Romantic", [], ["Six Piano Pieces Op 118", 1], 1],
["Intermezzo Op 118 No 2", "A Major", "Brahms", 6, 4, "Romantic", [], ["Six Piano Pieces Op 118", 2], 1],
["Intermezzo Op 118 No 4", "f minor", "Brahms", 3, 5, "Romantic", [], ["Six Piano Pieces Op 118", 4], 1],
["Intermezzo Op 118 No 6", "eb minor", "Brahms", 6, 4, "Romantic", [], ["Six Piano Pieces Op 118", 6], 1],
["Lullaby Op 49 No 4", "Eb Major", "Brahms", 3, 5, "Romantic", ["sleepy"], ["Six Piano Pieces Op 118", 1], 1],
["Piano Concerto No 1 Mvt 1", "d minor", "Brahms", 25, 4, "Romantic", [], "Piano Concerto No 1", 1],
["Piano Concerto No 1 Mvt 2", "D Major", "Brahms", 15, 4, "Romantic", [], "Piano Concerto No 1", 1],
["Piano Concerto No 1 Mvt 3", "d minor", "Brahms", 13, 4, "Romantic", [], "Piano Concerto No 1", 1],
["Piano Concerto No 2 Mvt 1", "Bb Major", "Brahms", 19, 3, "Romantic", ["legendary"], "Piano Concerto No 2", 1],
["Piano Concerto No 2 Mvt 2", "d minor", "Brahms", 10, 3, "Romantic", ["dark"], "Piano Concerto No 2", 1],
["Piano Concerto No 2 Mvt 3", "Bb Major", "Brahms", 15, 4, "Romantic", [], "Piano Concerto No 2", 1],
["Piano Concerto No 2 Mvt 4", "Bb Major", "Brahms", 10, 4, "Romantic", [], "Piano Concerto No 2", 1],
["Rhapsody Op 79 No 1", "b minor", "Brahms", 9, 2, "Romantic", ["stamina"], "Two Rhapsodies Op 79", 1],
["Rhapsody Op 79 No 2", "g minor", "Brahms", 7, 3, "Romantic", ["dark"], "Two Rhapsodies Op 79", 2],
["Romance Op 118 No 5", "F Major", "Brahms", 4, 4, "Romantic", [], ["Six Piano Pieces Op 118", 5], 1],
["Sonata No 1", "C Major", "Brahms", 25, 4, "Romantic", [], "Piano Sonatas", 1],
["Sonata No 2", "f# minor", "Brahms", 25, 4, "Romantic", [], "Piano Sonatas", 1],
["Sonata No 3", "Bb Major", "Brahms", 34, 4, "Romantic", [], "Piano Sonatas", 1],
["Variations on a Theme by Paganini Op 35", "a minor", "Brahms", 24, 4, "Romantic", [], "", 1],
["Etude Op 109 No 13", "d minor", "Burgmuller", 2, 5, "Romantic", [], "", 1],
["Andante Spianato Op 22 No 1", "G Major", "Chopin", 5, 2, "Romantic", ["uplifting", "sleepy"], "Andante spianato et grande polonaise brillante", 1],
["Ballade No 1", "g minor", "Chopin", 10, 3, "Romantic", [], "Four Ballades", 1],
["Ballade No 2", "F Major", "Chopin", 8, 2, "Romantic", ["legendary"], "Four Ballades", 1],
["Ballade No 3", "Ab Major", "Chopin", 7, 1, "Romantic", ["legendary"], "Four Ballades", 4],
["Ballade No 4", "f minor", "Chopin", 12, 4, "Romantic", [], "Four Ballades", 1],
["Barcarolle Op 60", "F# Major", "Chopin", 9, 4, "Romantic", [], "", 1],
["Berceuse Op 57", "Db Major", "Chopin", 5, 3, "Romantic", ["tender"], "", 1],
["Ecossaise Op 72 No 3", "D Major", "Chopin", 1, 5, "Romantic", [], "Three Ecossaises Op 72", 1],
["Ecossaise Op 72 No 4", "G Major", "Chopin", 1, 5, "Romantic", [], "Three Ecossaises Op 72", 1],
["Ecossaise Op 72 No 5", "Db Major", "Chopin", 1, 5, "Romantic", [], "Three Ecossaises Op 72", 1],
["Etude Op 10 No 1", "C Major", "Chopin", 2, 4, "Romantic", [], "Etudes Op 10", 1],
["Etude Op 10 No 2", "a minor", "Chopin", 2, 5, "Romantic", [], "Etudes Op 10", 1],
["Etude Op 10 No 3", "E Major", "Chopin", 5, 5, "Romantic", [], "Etudes Op 10", 1],
["Etude Op 10 No 4", "c# minor", "Chopin", 2, 5, "Romantic", [], "Etudes Op 10", 1],
["Etude Op 10 No 5", "Gb Major", "Chopin", 2, 5, "Romantic", [], "Etudes Op 10", 1],
["Etude Op 10 No 6", "eb minor", "Chopin", 5, 5, "Romantic", [], "Etudes Op 10", 1],
["Etude Op 10 No 7", "C Major", "Chopin", 2, 5, "Romantic", [], "Etudes Op 10", 1],
["Etude Op 10 No 8", "F Major", "Chopin", 3, 5, "Romantic", [], "Etudes Op 10", 1],
["Etude Op 10 No 9", "f minor", "Chopin", 3, 4, "Romantic", [], "Etudes Op 10", 1],
["Etude Op 10 No 10", "Ab Major", "Chopin", 3, 4, "Romantic", [], "Etudes Op 10", 1],
["Etude Op 10 No 11", "Eb Major", "Chopin", 3, 5, "Romantic", [], "Etudes Op 10", 1],
["Etude Op 10 No 12", "c minor", "Chopin", 3, 5, "Romantic", [], "Etudes Op 10", 1],
["Etude Op 25 No 1", "Ab Major", "Chopin", 4, 2, "Romantic", ["sleepy"], "Etudes Op 25", 1],
["Etude Op 25 No 2", "f minor", "Chopin", 2, 5, "Romantic", [], "Etudes Op 25", 1],
["Etude Op 25 No 3", "F Major", "Chopin", 2, 5, "Romantic", [], "Etudes Op 25", 1],
["Etude Op 25 No 4", "a minor", "Chopin", 2, 5, "Romantic", [], "Etudes Op 25", 1],
["Etude Op 25 No 5", "e minor", "Chopin", 4, 5, "Romantic", [], "Etudes Op 25", 1],
["Etude Op 25 No 6", "g# minor", "Chopin", 3, 5, "Romantic", [], "Etudes Op 25", 1],
["Etude Op 25 No 7", "c# minor", "Chopin", 6, 5, "Romantic", [], "Etudes Op 25", 1],
["Etude Op 25 No 8", "Db Major", "Chopin", 2, 5, "Romantic", [], "Etudes Op 25", 1],
["Etude Op 25 No 9", "Gb Major", "Chopin", 5, 5, "Romantic", ["stamina"], "Etudes Op 25", 1],
["Etude Op 25 No 10", "b minor", "Chopin", 5, 5, "Romantic", [], "Etudes Op 25", 1],
["Etude Op 25 No 11", "a minor", "Chopin", 4, 4, "Romantic", ["dark"], "Etudes Op 25", 1],
["Etude Op 25 No 12", "c minor", "Chopin", 3, 5, "Romantic", [], "Etudes Op 25", 1],
["Fantaisie Op 49", "Ab Major", "Chopin", 12, 1, "Romantic", ["legendary"], "Fantaisie Op 49", 2],
["Funeral March Op 72 No 2", "c minor", "Chopin", 6, 5, "Romantic", [], "", 1],
["Grande polonaise brillante Op 22 No 2", "Eb Major", "Chopin", 10, 4, "Romantic", [], "Andante spianato et grande polonaise brillante", 1],
["Impromptu No 1 Op 29", "Ab Major", "Chopin", 5, 4, "Romantic", [], "Four Impromptus", 1],
["Impromptu No 2 Op 36", "F# Major", "Chopin", 6, 5, "Romantic", [], "Four Impromptus", 1],
["Impromptu No 3 Op 51", "Gb Major", "Chopin", 6, 5, "Romantic", [], "Four Impromptus", 1],
["Impromptu No 4 Op 66", "c# minor", "Chopin", 5, 4, "Romantic", [], "Four Impromptus", 1],
["Mazurka Op 59 No 3", "f# minor", "Chopin", 4, 5, "Romantic", [], "", 1],
["Mazurka Op 67 No 4", "a minor", "Chopin", 4, 5, "Romantic", [], "", 1],
["Nocturne Op 9 No 1", "bb minor", "Chopin", 6, 4, "Romantic", ["sleepy"], "Nocturnes", 1],
["Nocturne Op 9 No 2", "Eb Major", "Chopin", 5, 4, "Romantic", ["sleepy"], "Nocturnes", 1],
["Nocturne Op 9 No 3", "B Major", "Chopin", 7, 4, "Romantic", [], "Nocturnes", 1],
["Nocturne Op 15 No 1", "F Major", "Chopin", 5, 3, "Romantic", ["sleepy"], "Nocturnes", 1],
["Nocturne Op 15 No 2", "F# Major", "Chopin", 4, 4, "Romantic", ["sleepy"], "Nocturnes", 1],
["Nocturne Op 15 No 3", "g minor", "Chopin", 5, 5, "Romantic", [], "Nocturnes", 1],
["Nocturne Op 27 No 1", "c# minor", "Chopin", 6, 4, "Romantic", [], "Nocturnes", 1],
["Nocturne Op 27 No 2", "Db Major", "Chopin", 8, 4, "Romantic", ["sleepy"], "Nocturnes", 1],
["Nocturne Op 32 No 1", "B Major", "Chopin", 6, 4, "Romantic", ["sleepy"], "Nocturnes", 1],
["Nocturne Op 32 No 2", "Ab Major", "Chopin", 6, 4, "Romantic", [], "Nocturnes", 1],
["Nocturne Op 37 No 1", "g minor", "Chopin", 7, 5, "Romantic", [], "Nocturnes", 1],
["Nocturne Op 37 No 2", "G Major", "Chopin", 6, 3, "Romantic", ["sleepy"], "Nocturnes", 1],
["Nocturne Op 48 No 1", "c minor", "Chopin", 7, 3, "Romantic", ["sad"], "Nocturnes", 1],
["Nocturne Op 48 No 2", "f# minor", "Chopin", 7, 5, "Romantic", [], "Nocturnes", 1],
["Nocturne Op 55 No 1", "f minor", "Chopin", 5, 4, "Romantic", [], "Nocturnes", 1],
["Nocturne Op 55 No 2", "Eb Major", "Chopin", 5, 5, "Romantic", [], "Nocturnes", 1],
["Nocturne Op 62 No 1", "B Major", "Chopin", 8, 5, "Romantic", [], "Nocturnes", 1],
["Nocturne Op 62 No 2", "E Major", "Chopin", 6, 5, "Romantic", [], "Nocturnes", 1],
["Nocturne Op 72 No 1", "e minor", "Chopin", 5, 5, "Romantic", [], "Nocturnes", 1],
["Nocturne No 20 Op Posth", "c# minor", "Chopin", 4, 4, "Romantic", [], "Nocturnes", 1],
["Nocturne No 21 Op Posth", "c minor", "Chopin", 4, 5, "Romantic", [], "Nocturnes", 1],
["Piano Concerto No 1 Op 11 Mvt 1", "e minor", "Chopin", 21, 1, "Romantic", ["legendary"], "Piano Concerto No 1", 1],
["Piano Concerto No 1 Op 11 Mvt 2", "E Major", "Chopin", 10, 1, "Romantic", ["uplifting"], "Piano Concerto No 1", 1],
["Piano Concerto No 1 Op 11 Mvt 3", "E Major", "Chopin", 10, 1, "Romantic", ["stamina", "party"], "Piano Concerto No 1", 1],
["Piano Concerto No 2 Op 21 Mvt 1", "f minor", "Chopin", 16, 2, "Romantic", ["legendary"], "Piano Concerto No 2", 1],
["Piano Concerto No 2 Op 21 Mvt 2", "Ab Major", "Chopin", 12, 3, "Romantic", ["tender"], "Piano Concerto No 2", 1],
["Piano Concerto No 2 Op 21 Mvt 3", "f minor", "Chopin", 10, 2, "Romantic", [], "Piano Concerto No 2", 1],
["Polonaise Fantaisie Op 61", "Ab Major", "Chopin", 14, 4, "Romantic", ["experimental"], "", 1],
["Polonaise Op 26 No 1", "c# minor", "Chopin", 8, 4, "Romantic", ["dark"], "Seven Polonaises", 1],
["Polonaise Op 26 No 2", "eb minor", "Chopin", 8, 3, "Romantic", [], "Seven Polonaises", 1],
["Polonaise Op 40 No 1", "A Major", "Chopin", 5, 3, "Romantic", ["stamina", "party"], "Seven Polonaises", 1],
["Polonaise Op 40 No 2", "c minor", "Chopin", 8, 5, "Romantic", [], "Seven Polonaises", 1],
["Polonaise Op 44", "f# minor", "Chopin", 11, 4, "Romantic", ["dark", "stamina"], "Seven Polonaises", 1],
["Polonaise Op 53", "Ab Major", "Chopin", 7, 3, "Romantic", ["stamina", "party"], "Seven Polonaises", 1],
["Polonaise Op 71 No 1", "d minor", "Chopin", 6, 5, "Romantic", [], "", 1],
["Polonaise Op 71 No 2", "Bb Major", "Chopin", 7, 4, "Romantic", [], "", 1],
["Polonaise Op 71 No 3", "f minor", "Chopin", 8, 5, "Romantic", [], "", 1],
["Polonaise Op Posth B 1", "g minor", "Chopin", 3, 5, "Romantic", [], "", 1],
["Polonaise Op Posth B 6", "g# minor", "Chopin", 7, 5, "Romantic", [], "", 1],
["Prelude Op 28 No 1", "C Major", "Chopin", 1, 4, "Romantic", [], "", 1],
["Prelude Op 28 No 4", "e minor", "Chopin", 3, 4, "Romantic", ["tender"], "", 1],
["Prelude Op 28 No 11", "B Major", "Chopin", 1, 5, "Romantic", [], "", 1],
["Prelude Op 28 No 15", "Db Major", "Chopin", 6, 2, "Romantic", ["tender", "zen"], "", 1],
["Prelude Op 28 No 16", "bb minor", "Chopin", 2, 5, "Romantic", [], "", 1],
["Prelude Op 28 No 17", "Ab Major", "Chopin", 4, 4, "Romantic", ["sleepy"], "", 1],
["Prelude Op 28 No 19", "Eb Major", "Chopin", 2, 5, "Romantic", [], "", 1],
["Prelude Op 28 No 24", "d minor", "Chopin", 3, 5, "Romantic", [], "", 1],
["Scherzo No 1 Op 20", "b minor", "Chopin", 10, 3, "Romantic", ["experimental"], "Four Scherzos", 1],
["Scherzo No 2 Op 31", "bb minor", "Chopin", 10, 1, "Romantic", [], "Four Scherzos", 2],
["Scherzo No 3 Op 39", "C# Major", "Chopin", 8, 4, "Romantic", ["experimental"], "Four Scherzos", 1],
["Scherzo No 4 Op 54", "E Major", "Chopin", 11, 3, "Romantic", ["experimental"], "Four Scherzos", 1],
["Sonata No 1 Op 4", "c minor", "Chopin", 26, 3, "Romantic", ["legendary"], "Three Sonatas", 1],
["Sonata No 2 Op 35", "bb minor", "Chopin", 24, 3, "Romantic", ["legendary"], "Three Sonatas", 2],
["Sonata No 3 Op 58", "b minor", "Chopin", 25, 2, "Romantic", ["legendary"], "Three Sonatas", 1],
["Tarantella Op 43", "Ab Major", "Chopin", 4, 4, "Romantic", [], "", 1],
["Waltz No 1 Op 18", "Eb Major", "Chopin", 5, 3, "Romantic", [], "Waltzes", 1],
["Waltz No 2 Op 34 No 1", "Ab Major", "Chopin", 5, 5, "Romantic", [], "Waltzes", 1],
["Waltz No 3 Op 34 No 2", "a minor", "Chopin", 6, 4, "Romantic", [], "Waltzes", 1],
["Waltz No 4 Op 34 No 3", "F Major", "Chopin", 3, 5, "Romantic", [], "Waltzes", 1],
["Waltz No 5 Op 42", "Ab Major", "Chopin", 4, 4, "Romantic", [], "Waltzes", 1],
["Waltz No 6 Op 64 No 1", "Db Major", "Chopin", 2, 4, "Romantic", [], "Waltzes", 1],
["Waltz No 7 Op 64 No 2", "c# minor", "Chopin", 3, 4, "Romantic", [], "Waltzes", 1],
["Waltz No 8 Op 64 No 3", "Ab Major", "Chopin", 4, 5, "Romantic", [], "Waltzes", 1],
["Waltz No 9 Op 69 No 1", "Ab Major", "Chopin", 4, 4, "Romantic", [], "Waltzes", 1],
["Waltz No 10 Op 69 No 2", "b minor", "Chopin", 3, 4, "Romantic", [], "Waltzes", 1],
["Waltz No 11 Op 70 No 1", "F# Major", "Chopin", 2, 5, "Romantic", [], "Waltzes", 1],
["Waltz No 12 Op 70 No 2", "f minor", "Chopin", 4, 5, "Romantic", [], "Waltzes", 1],
["Waltz No 13 Op 70 No 3", "Db Major", "Chopin", 3, 5, "Romantic", [], "Waltzes", 1],
["Waltz No 14 B 56", "e minor", "Chopin", 3, 4, "Romantic", ["dark"], "Waltzes", 1],
["Waltz No 15 B 44", "E Major", "Chopin", 3, 5, "Romantic", [], "Waltzes", 1],
["Waltz No 16 B 21", "Ab Major", "Chopin", 3, 5, "Romantic", [], "Waltzes", 1],
["Waltz No 17 B 46", "Eb Major", "Chopin", 4, 4, "Romantic", [], "Waltzes", 1],
["Waltz No 18 B 133", "Eb Major", "Chopin", 3, 4, "Romantic", [], "Waltzes", 1],
["Waltz No 19 Op Posth B 150", "a minor", "Chopin", 2, 5, "Romantic", [], "Waltzes", 1],
["Appalachian Spring", "A Major", "Copland", 26, 4, "Contemporary", [], "Appalachian Spring", 1],
["Cat and Mouse", "a minor", "Copland", 4, 4, "Contemporary", ["troll"], "", 1],
["And the Moon Sets over the Temple That Was", "e minor", "Debussy", 5, 5, "Romantic", ["impressions"], ["Images Book 2", 2], 1],
["Arabesque No 1", "E Major", "Debussy", 5, 3, "Romantic", ["sleepy", "impressions"], "Two Arabesques", 1],
["Arabesque No 2", "G Major", "Debussy", 4, 4, "Romantic", [], "Two Arabesques", 1],
["Ballade", "F Major", "Debussy", 8, 4, "Romantic", [], "", 1],
["Ballet", "D Major", "Debussy", 4, 3, "Romantic", [], ["Petite Suite", 4], 1],
["Bells Through the Leaves", "", "Debussy", 5, 4, "Romantic", ["impressions"], ["Images Book 2", 1], 1],
["Clair De Lune", "Db Major", "Debussy", 6, 2, "Romantic", ["tender", "sleepy", "zen"], ["Suite Bergamasque", 3], 1],
["Cortege", "E Major", "Debussy", 4, 4, "Romantic", [], ["Petite Suite", 2], 1],
["Danse Bohemienne", "b minor", "Debussy", 2, 4, "Romantic", [], "", 1],
["Doctor Gradus ad Parnassum", "C Major", "Debussy", 2, 5, "Romantic", [], ["Childrens Corner", 1], 1],
["En Bateau", "G Major", "Debussy", 4, 3, "Romantic", [], ["Petite Suite", 1], 1],
["Evening in Granada", "f# minor", "Debussy", 6, 3, "Romantic", ["impressions"], ["Estampes", 2], 1],
["Gardens in the Rain", "e minor", "Debussy", 4, 3, "Romantic", [], ["Estampes", 3], 1],
["Goldfish", "F# Major", "Debussy", 4, 5, "Romantic", ["impressions"], ["Images Book 2", 3], 1],
["Golliwoggs Cakewalk", "Eb Major", "Debussy", 4, 5, "Romantic", [], ["Childrens Corner", 6], 1],
["Hommage a Rameau", "", "Debussy", 6, 5, "Romantic", ["impressions"], ["Images Book 1", 2], 1],
["Jimbos Lullaby", "d minor", "Debussy", 4, 5, "Romantic", [], ["Childrens Corner", 2], 1],
["Lisle Joyeuse", "A Major", "Debussy", 6, 3, "Romantic", ["impressions"], "", 1],
["Menuet from Suite Bergamasque", "a minor", "Debussy", 5, 4, "Romantic", [], ["Suite Bergamasque", 2], 1],
["Menuet from Petite Suite", "G Major", "Debussy", 4, 4, "Romantic", [], ["Petite Suite", 3], 1],
["Mouvement", "C Major", "Debussy", 4, 4, "Romantic", ["stamina"], ["Images Book 1", 3], 1],
["Nocturne L 82", "Db Major", "Debussy", 7, 4, "Romantic", ["impressions"], "", 1],
["Pagodas", "B Major", "Debussy", 6, 3, "Romantic", ["impressions"], ["Estampes", 1], 1],
["Prelude from Suite Bergamasque", "F Major", "Debussy", 5, 4, "Romantic", [], ["Suite Bergamasque", 1], 1],
["Prelude L 117 No 1", "Bb Major", "Debussy", 4, 5, "Romantic", ["impressions"], "Preludes L 117", 1],
["Prelude L 117 No 2", "", "Debussy", 5, 5, "Romantic", ["impressions"], "Preludes L 117", 1],
["Prelude L 117 No 3", "", "Debussy", 3, 5, "Romantic", [], "Preludes L 117", 1],
["Prelude L 117 No 4", "A Major", "Debussy", 5, 5, "Romantic", ["impressions"], "Preludes L 117", 1],
["Prelude L 117 No 5", "B Major", "Debussy", 4, 3, "Romantic", ["impressions", "party"], "Preludes L 117", 1],
["Prelude L 117 No 6", "d minor", "Debussy", 5, 5, "Romantic", ["impressions"], "Preludes L 117", 1],
["Prelude L 117 No 7", "", "Debussy", 4, 4, "Romantic", ["impressions"], "Preludes L 117", 1],
["Prelude L 117 No 8", "Gb Major", "Debussy", 3, 5, "Romantic", ["impressions"], "Preludes L 117", 1],
["Prelude L 117 No 9", "Bb Major", "Debussy", 3, 5, "Romantic", ["impressions"], "Preludes L 117", 1],
["Prelude L 117 No 10", "C Major", "Debussy", 7, 4, "Romantic", ["impressions"], "Preludes L 117", 1],
["Prelude L 117 No 11", "f minor", "Debussy", 3, 5, "Romantic", ["impressions"], "Preludes L 117", 1],
["Prelude L 117 No 12", "G Major", "Debussy", 3, 4, "Romantic", ["impressions"], "Preludes L 117", 1],
["Passapied", "f# minor", "Debussy", 4, 5, "Romantic", [], ["Suite Bergamasque", 4], 1],
["Reflections in the Water", "Db Major", "Debussy", 5, 3, "Romantic", ["sleepy", "impressions"], ["Images Book 1", 1], 1],
["Reverie", "F Major", "Debussy", 5, 4, "Romantic", [], "", 1],
["Serenade for the Doll", "E Major", "Debussy", 3, 3, "Romantic", [], ["Childrens Corner", 3], 1],
["The Little Shepherd", "A Major", "Debussy", 3, 5, "Romantic", [], ["Childrens Corner", 5], 1],
["The Snow is Dancing", "d minor", "Debussy", 3, 5, "Romantic", [], ["Childrens Corner", 4], 1],
["Valse Romantique", "f minor", "Debussy", 3, 5, "Romantic", [], "", 1],
["Cello Concerto Op 104 Mvt 1", "b minor", "Dvorak", 16, 4, "Romantic", [], "Cello Concerto Op 104", 1],
["Cello Concerto Op 104 Mvt 2", "G Major", "Dvorak", 14, 4, "Romantic", ["uplifting"], "Cello Concerto Op 104", 1],
["Cello Concerto Op 104 Mvt 3", "b minor", "Dvorak", 14, 5, "Romantic", [], "Cello Concerto Op 104", 1],
["New World Symphony Mvt 1", "e minor", "Dvorak", 13, 5, "Romantic", [], "New World Symphony", 1],
["New World Symphony Mvt 2", "Db Major", "Dvorak", 13, 4, "Romantic", ["uplifting"], "New World Symphony", 1],
["New World Symphony Mvt 3", "e minor", "Dvorak", 9, 5, "Romantic", [], "New World Symphony", 1],
["New World Symphony Mvt 4", "e minor", "Dvorak", 13, 5, "Romantic", [], "New World Symphony", 1],
["Pavane Op 50", "f# minor", "Faure", 8, 4, "Romantic", [], "", 1],
["Sicilienne Op 80 No 4", "g minor", "Faure", 5, 4, "Romantic", ["tender"], "", 1],
["Nocturne H 24", "Eb Major", "Field", 4, 5, "Romantic", ["sleepy"], "", 1],
["Nocturne H 25", "c minor", "Field", 4, 5, "Romantic", ["sleepy"], "", 1],
["Nocturne H 37", "Bb Major", "Field", 4, 4, "Romantic", ["sleepy"], "", 1],
["Nocturne H 56", "Eb Major", "Field", 6, 4, "Romantic", ["sleepy"], "", 1],
["Entry of the Gladiators", "Ab Major", "Fucik", 4, 4, "Contemporary", [], "", 1],
["Rhapsody in Blue", "Bb Major", "Gershwin", 17, 4, "Contemporary", [], "", 1],
["Danza de la Moza Donosa", "C Major", "Ginastera", 3, 5, "Contemporary", [], ["Danzas Argentinas", 2], 1],
["Danza del Gaucho Matrero", "a minor", "Ginastera", 3, 5, "Contemporary", [], ["Danzas Argentinas", 3], 1],
["Danza del Viejo Boyero", "C Major", "Ginastera", 2, 5, "Contemporary", [], ["Danzas Argentinas", 1], 1],
["Harp Concerto Mvt 2", "Cb Major", "Gliere", 6, 5, "Contemporary", [], "Harp Concerto", 1],
["Harp Concerto Mvt 1", "Eb Major", "Gliere", 12, 5, "Contemporary", [], "Harp Concerto", 1],
["Harp Concerto Mvt 2", "Cb Major", "Gliere", 6, 5, "Contemporary", [], "Harp Concerto", 1],
["Harp Concerto Mvt 3", "Eb Major", "Gliere", 13, 4, "Contemporary", [], "Harp Concerto", 1],
["Horn Concerto Mvt 1", "Bb Major", "Gliere", 13, 5, "Contemporary", [], "Horn Concerto", 1],
["Horn Concerto Mvt 2", "Eb Major", "Gliere", 7, 5, "Contemporary", ["tender"], "Horn Concerto", 1],
["Horn Concerto Mvt 3", "Bb Major", "Gliere", 7, 5, "Contemporary", [], "Horn Concerto", 1],
["The Lark", "bb minor", "Glinka", 6, 3, "Romantic", ["sad"], "", 1],
["Anitras Dance", "a minor", "Grieg", 4, 4, "Romantic", [], ["Peer Gynt Suite No 1", 3], 1],
["Arabian Dance", "C Major", "Grieg", 5, 5, "Romantic", [], ["Peer Gynt Suite No 2", 2], 1],
["In the Hall of the Mountain King", "b minor", "Grieg", 3, 3, "Romantic", [], ["Peer Gynt Suite No 1", 4], 1],
["March of the Trolls Op 54 No 3", "d minor", "Grieg", 2, 3, "Romantic", ["stamina"], "", 1],
["Morning Mood", "E Major", "Grieg", 5, 2, "Romantic", [], ["Peer Gynt Suite No 1", 1], 1],
["Notturno Op 54 No 4", "a minor", "Grieg", 4, 4, "Romantic", [], "", 1],
["Piano Concerto Op 16 Mvt 1", "a minor", "Grieg", 15, 3, "Romantic", [], "Piano Concerto Op 16", 1],
["Piano Concerto Op 16 Mvt 2", "Db Major", "Grieg", 8, 3, "Romantic", ["uplifting", "tender", "sleepy"], "Piano Concerto Op 16", 1],
["Piano Concerto Op 16 Mvt 3", "a minor", "Grieg", 11, 3, "Romantic", ["stamina"], "Piano Concerto Op 16", 1],
["Piano Sonata No 7", "e minor", "Grieg", 19, 4, "Romantic", [], "", 1],
["The Abuction of the Bride Ingrids Lament", "g minor", "Grieg", 4, 5, "Romantic", [], ["Peer Gynt Suite No 2", 1], 1],
["The Death of Aase", "b minor", "Grieg", 5, 4, "Romantic", [], ["Peer Gynt Suite No 1", 2], 1],
["Peer Gynts Homecoming", "f# minor", "Grieg", 3, 4, "Romantic", [], ["Peer Gynt Suite No 2", 3], 1],
["Solveigs Song", "a minor", "Grieg", 5, 4, "Romantic", [], ["Peer Gynt Suite No 2", 4], 1],
["Piano Concerto No 11 Mvt 1", "D Major", "Haydn", 9, 4, "Classical", [], "Piano Concerto No 11", 1],
["Piano Concerto No 11 Mvt 2", "A Major", "Haydn", 9, 4, "Classical", [], "Piano Concerto No 11", 1],
["Piano Concerto No 11 Mvt 3", "D Major", "Haydn", 5, 4, "Classical", ["stamina"], "Piano Concerto No 11", 1],
["Piano Sonata No 50", "D Major", "Haydn", 6, 4, "Classical", ["stamina"], "", 1],
["Symphony No 47 Mvt 3", "G Major", "Haydn", 3, 5, "Classical", ["troll"], "", 1],
["Concert Etude Op 40 No 1", "C Major", "Kasputin", 3, 5, "Contemporary", [], "Concert Etudes Op 40", 1],
["Concert Etude Op 40 No 2", "Ab Major", "Kasputin", 3, 5, "Contemporary", [], "Concert Etudes Op 40", 1],
["Concert Etude Op 40 No 3", "e minor", "Kasputin", 3, 5, "Contemporary", [], "Concert Etudes Op 40", 1],
["Concert Etude Op 40 No 4", "B Major", "Kasputin", 4, 5, "Contemporary", [], "Concert Etudes Op 40", 1],
["Concert Etude Op 40 No 5", "D Major", "Kasputin", 3, 5, "Contemporary", [], "Concert Etudes Op 40", 1],
["Concert Etude Op 40 No 6", "Bb Major", "Kasputin", 3, 5, "Contemporary", [], "Concert Etudes Op 40", 1],
["Concert Etude Op 40 No 7", "Db Major", "Kasputin", 4, 5, "Contemporary", [], "Concert Etudes Op 40", 1],
["Concert Etude Op 40 No 8", "f minor", "Kasputin", 3, 5, "Contemporary", [], "Concert Etudes Op 40", 1],
["Piano Concerto No 2 Mvt 1", "C Major", "Kasputin", 6, 5, "Contemporary", [], "Piano Concerto No 2", 1],
["Piano Concerto No 2 Mvt 2", "Ab Major", "Kasputin", 6, 5, "Contemporary", [], "Piano Concerto No 2", 1],
["Piano Concerto No 2 Mvt 3", "C Major", "Kasputin", 6, 5, "Contemporary", [], "Piano Concerto No 2", 1],
["Galop", "Bb Major", "Khachaturian", 3, 4, "Contemporary", ["stamina", "party"], "", 1],
["Mazurka", "Eb Major", "Khachaturian", 3, 4, "Contemporary", ["stamina"], "", 1],
["Sonatina in C Major Mvt 1", "C Major", "Khachaturian", 2, 5, "Contemporary", ["troll"], "", 1],
["Waltz from Masquerade Suite", "a minor", "Khachaturian", 5, 4, "Contemporary", [], "", 1],
["Liebeslied", "a minor", "Kreisler", 4, 5, "Contemporary", ["sad"], "", 1],
["Andalucia", "D Major", "Lecuona", 3, 4, "Contemporary", [], "", 1],
["Danza Lucumi", "Db Major", "Lecuona", 3, 4, "Contemporary", [], "", 1],
["Malaguena", "c# minor", "Lecuona", 4, 4, "Contemporary", [], "", 1],
["Gargoyles", "a minor", "Liebermann", 10, 4, "Contemporary", ["troll"], "", 1],
["Au bord dune source", "Ab Major", "Liszt", 4, 4, "Romantic", ["tender", "sleepy"], ["Years of Pilgrimage 1: Switzerland S 160", 4], 1],
["Au lac de Wallenstadt", "Ab Major", "Liszt", 4, 2, "Romantic", ["tender", "sleepy"], ["Years of Pilgrimage 1: Switzerland S 160", 2], 1],
["Ave Maria S 173 No 2", "Bb Major", "Liszt", 9, 5, "Romantic", ["tender", "sleepy"], "", 1],
["Ballade No 1 S 170", "Db Major", "Liszt", 8, 4, "Romantic", ["experimental"], "Ballades", 1],
["Ballade No 2 S 171", "b minor", "Liszt", 16, 4, "Romantic", ["experimental"], "Ballades", 1],
["Benediction de Dieu dans la solitude S 173 No 3", "F# Major", "Liszt", 18, 1, "Romantic", ["legendary", "tender", "sleepy", "zen"], "", 2],
["Berceuse S 186 No 7", "F# Major", "Liszt", 4, 4, "Romantic", ["tender", "sleepy"], "", 1],
["Chapelle de Guillaume Tell", "C Major", "Liszt", 6, 5, "Romantic", [], ["Years of Pilgrimage 1: Switzerland S 160", 1], 1],
["Consolation No 1", "E Major", "Liszt", 2, 4, "Romantic", ["tender", "sleepy"], "Six Consolations S 172", 1],
["Consolation No 2", "E Major", "Liszt", 4, 4, "Romantic", ["tender", "sleepy"], "Six Consolations S 172", 1],
["Consolation No 3", "Db Major", "Liszt", 6, 2, "Romantic", ["tender", "sleepy", "zen"], "Six Consolations S 172", 1],
["Consolation No 4", "Db Major", "Liszt", 4, 5, "Romantic", ["tender"], "Six Consolations S 172", 1],
["Consolation No 5", "E Major", "Liszt", 3, 4, "Romantic", ["tender", "sleepy"], "Six Consolations S 172", 1],
["Consolation No 6", "E Major", "Liszt", 3, 4, "Romantic", ["tender", "sleepy"], "Six Consolations S 172", 1],
["Eglogue", "Ab Major", "Liszt", 4, 3, "Romantic", ["tender", "sleepy"], ["Years of Pilgrimage 1: Switzerland S 160", 6], 1],
["Elegie S 168", "Ab Major", "Liszt", 8, 4, "Romantic", [], "", 1],
["Etude S 141 No 1", "g minor", "Liszt", 5, 4, "Romantic", [], ["Six Grand Paganini Etudes S 141", 1], 1],
["Etude S 141 No 2", "Eb Major", "Liszt", 6, 4, "Romantic", [], ["Six Grand Paganini Etudes S 141", 2], 1],
["Etude S 141 No 4", "E Major", "Liszt", 2, 4, "Romantic", [], ["Six Grand Paganini Etudes S 141", 4], 1],
["Etude S 141 No 5", "E Major", "Liszt", 3, 4, "Romantic", [], ["Six Grand Paganini Etudes S 141", 5], 1],
["Etude S 141 No 6", "a minor", "Liszt", 5, 4, "Romantic", [], ["Six Grand Paganini Etudes S 141", 6], 1],
["Galop de Bal S 220", "Bb Major", "Liszt", 1, 4, "Romantic", ["stamina"], "", 1],
["Gnomenreigen", "f# minor", "Liszt", 3, 4, "Romantic", [], ["Two Concert Etudes S 145", 2], 1],
["Grand Galop Chromatique S 219", "Eb Major", "Liszt", 4, 3, "Romantic", ["stamina", "party"], "", 1],
["Hungarian Fantasy S 123", "e minor", "Liszt", 16, 4, "Romantic", [], "Hungarian Fantasy S 123", 1],
["Hungarian Rhapsody S 244 No 2", "c# minor", "Liszt", 9, 2, "Romantic", ["dark"], "", 1],
["Il Lamento", "Ab Major", "Liszt", 10, 3, "Romantic", [], ["Three Concert Etudes S 144", 1], 1],
["La Campanella", "g# minor", "Liszt", 5, 3, "Romantic", [], ["Six Grand Paganini Etudes S 141", 3], 1],
["La Leggierezza", "f minor", "Liszt", 5, 2, "Romantic", ["dark"], ["Three Concert Etudes S 144", 2], 4],
["Le mal du pays", "e minor", "Liszt", 6, 5, "Romantic", [], ["Years of Pilgrimage 1: Switzerland S 160", 7], 1],
["Les cloches de Geneve", "B Major", "Liszt", 6, 5, "Romantic", [], ["Years of Pilgrimage 1: Switzerland S 160", 8], 1],
["Liebestraum No 1", "Ab Major", "Liszt", 8, 4, "Romantic", ["tender"], "Liebestraume S 541", 1],
["Liebestraum No 2", "Eb Major", "Liszt", 5, 4, "Romantic", [], "Liebestraume S 541", 1],
["Liebestraum No 3", "Ab Major", "Liszt", 5, 2, "Romantic", ["tender"], "Liebestraume S 541", 1],
["Mephisto Waltz S 514 No 1", "A Major", "Liszt", 12, 3, "Romantic", ["experimental", "stamina"], "", 1],
["Mephisto Waltz S 514 No 3", "d# minor", "Liszt", 10, 4, "Romantic", ["experimental"], "", 1],
["Mephisto Waltz S 514 No 4", "D Major", "Liszt", 4, 5, "Romantic", ["experimental"], "", 1],
["Orage", "c minor", "Liszt", 5, 5, "Romantic", ["dark"], ["Years of Pilgrimage 1: Switzerland S 160", 5], 1],
["Pastorale", "E Major", "Liszt", 2, 5, "Romantic", [], ["Years of Pilgrimage 1: Switzerland S 160", 3], 1],
["Piano Concerto No 1", "Eb Major", "Liszt", 19, 3, "Romantic", ["experimental"], "Piano Concerto No 1", 1],
["Piano Concerto No 2", "A Major", "Liszt", 23, 4, "Romantic", ["experimental"], "Piano Concerto No 2", 1],
["Psallite S 186 No 1", "F Major", "Liszt", 3, 5, "Romantic", [], "", 1],
["Rondo El Contrabandista S 252", "g minor", "Liszt", 12, 4, "Romantic", ["experimental", "stamina"], "", 1],
["Russian Galop S 478", "Bb Major", "Liszt", 3, 4, "Romantic", ["stamina"], "", 1],
["Seven Brilliant Variations on a Theme of Rossini S 149", "A Major", "Liszt", 10, 4, "Romantic", [], "", 1],
["Sonata S 178", "b minor", "Liszt", 31, 2, "Romantic", ["dark", "experimental", "legendary"], "Sonata S 178", 1],
["Spanish Fantasy S 253", "D Major", "Liszt", 13, 4, "Romantic", [], "", 1],
["Tarantella S 162", "Eb Major", "Liszt", 10, 5, "Romantic", [], "", 1],
["The Fountains of the Villa dEste S 163 No 4", "F# Major", "Liszt", 8, 5, "Romantic", ["tender", "sleepy"], "", 1],
["The Nightingale S 250", "c# minor", "Liszt", 4, 4, "Romantic", [], "", 1],
["Transcendental Etude S 139 No 1", "C Major", "Liszt", 1, 5, "Romantic", [], "", 1],
["Transcendental Etude S 139 No 3", "F Major", "Liszt", 5, 5, "Romantic", ["sleepy"], "", 1],
["Transcendental Etude S 139 No 8", "c minor", "Liszt", 6, 5, "Romantic", [], "", 1],
["Un Sospiro", "Db Major", "Liszt", 6, 1, "Romantic", ["tender", "sleepy", "zen"], ["Three Concert Etudes S 144", 3], 4],
["Waldesrauschen", "Db Major", "Liszt", 5, 2, "Romantic", ["tender", "sleepy", "zen"], ["Two Concert Etudes S 145", 1], 1],
["Intermezzo from Cavalleria Rusticana", "F Major", "Mascagni", 4, 4, "Romantic", ["sleepy"], "", 1],
["Meditation from Thais", "D Major", "Massenet", 5, 4, "Romantic", ["tender"], "", 1],
["A Midsummer Nights Dream Overture", "E Major", "Mendelssohn", 13, 4, "Romantic", [], ["A Midsummer Nights Dream", 1], 1],
["Caprice Op 5", "f# minor", "Mendelssohn", 7, 4, "Romantic", [], "", 1],
["Caprice Op 33 No 1", "a minor", "Mendelssohn", 9, 4, "Romantic", [], "Three Caprices Op 33", 1],
["Caprice Op 33 No 2", "E Major", "Mendelssohn", 9, 4, "Romantic", [], "Three Caprices Op 33", 1],
["Caprice Op 33 No 3", "bb minor", "Mendelssohn", 7, 4, "Romantic", [], "Three Caprices Op 33", 1],
["Dance of the Clowns", "B Major", "Mendelssohn", 2, 4, "Romantic", [], ["A Midsummer Nights Dream", 6], 1],
["Fantasia Op 15", "E Major", "Mendelssohn", 9, 4, "Romantic", [], "", 1],
["Intermezzo", "a minor", "Mendelssohn", 5, 4, "Romantic", [], ["A Midsummer Nights Dream", 3], 1],
["Nocturne", "E Major", "Mendelssohn", 6, 4, "Romantic", ["uplifting"], ["A Midsummer Nights Dream", 4], 1],
["Piano Concerto No 1 Mvt 1", "g minor", "Mendelssohn", 7, 3, "Romantic", ["dark", "stamina"], "Piano Concerto No 1", 1],
["Piano Concerto No 1 Mvt 2", "E Major", "Mendelssohn", 7, 3, "Romantic", ["tender"], "Piano Concerto No 1", 1],
["Piano Concerto No 1 Mvt 3", "G Major", "Mendelssohn", 6, 3, "Romantic", ["stamina", "party"], "Piano Concerto No 1", 1],
["Piano Concerto No 2 Mvt 1", "d minor", "Mendelssohn", 11, 4, "Romantic", ["dark"], "Piano Concerto No 2", 1],
["Piano Concerto No 2 Mvt 2", "Bb Major", "Mendelssohn", 8, 3, "Romantic", ["tender", "sleepy", "uplifting"], "Piano Concerto No 2", 1],
["Piano Concerto No 2 Mvt 3", "D Major", "Mendelssohn", 8, 4, "Romantic", [], "Piano Concerto No 2", 1],
["Rondo Capriccioso Op 14", "e minor", "Mendelssohn", 7, 3, "Romantic", [], "", 1],
["Scherzo", "g minor", "Mendelssohn", 5, 4, "Romantic", [], ["A Midsummer Nights Dream", 2], 1],
["Scherzo a Capriccio", "f# minor", "Mendelssohn", 7, 5, "Romantic", [], "", 1],
["Sonata Op 105", "g minor", "Mendelssohn", 18, 4, "Romantic", [], "", 1],
["Song Without Words Op 19 No 1", "E Major", "Mendelssohn", 4, 5, "Romantic", ["tender"], "", 1],
["Song Without Words Op 19 No 6", "g minor", "Mendelssohn", 2, 5, "Romantic", ["sad"], "", 1],
["Song Without Words Op 30 No 6", "f# minor", "Mendelssohn", 3, 5, "Romantic", ["sad"], "", 1],
["Song Without Words Op 38 No 2", "c minor", "Mendelssohn", 2, 5, "Romantic", [], "", 1],
["Symphony No 4 Mvt 1", "A Major", "Mendelssohn", 11, 3, "Romantic", ["stamina", "party"], "", 1],
["The Hebrides Overture", "b minor", "Mendelssohn", 11, 3, "Romantic", [], "", 1],
["Violin Concerto Mvt 1", "e minor", "Mendelssohn", 13, 5, "Romantic", ["sad"], "Violin Concerto", 1],
["Violin Concerto Mvt 2", "C Major", "Mendelssohn", 9, 5, "Romantic", ["tender"], "Violin Concerto", 1],
["Violin Concerto Mvt 3", "E Major", "Mendelssohn", 7, 5, "Romantic", [], "Violin Concerto", 1],
["Wedding March", "C Major", "Mendelssohn", 5, 4, "Romantic", [], ["A Midsummer Nights Dream", 5], 1],
["Piano Concerto Op 59 Mvt 1", "E Major", "Moszkowski", 13, 4, "Romantic", [], "Piano Concerto Op 59", 1],
["Piano Concerto Op 59 Mvt 2", "c# minor", "Moszkowski", 9, 4, "Romantic", ["dark"], "Piano Concerto Op 59", 1],
["Piano Concerto Op 59 Mvt 3", "c# minor", "Moszkowski", 8, 4, "Romantic", ["stamina"], "Piano Concerto Op 59", 1],
["Piano Concerto Op 59 Mvt 4", "E Major", "Moszkowski", 10, 4, "Romantic", ["stamina"], "Piano Concerto Op 59", 1],
["Clarinet Concerto Mvt 1", "A Major", "Mozart", 13, 3, "Classical", [], "Clarinet Concerto", 1],
["Clarinet Concerto Mvt 2", "D Major", "Mozart", 8, 3, "Classical", ["uplifting"], "Clarinet Concerto", 1],
["Clarinet Concerto Mvt 3", "A Major", "Mozart", 9, 4, "Classical", [], "Clarinet Concerto", 1],
["Eine Kleine Nachtmusik", "G Major", "Mozart", 6, 5, "Classical", [], "", 1],
["Fantasia K 397", "d minor", "Mozart", 6, 4, "Classical", ["sad"], "", 1],
["Piano Concerto No 21 Mvt 1", "C Major", "Mozart", 14, 4, "Classical", [], "Piano Concerto No 21", 1],
["Piano Concerto No 21 Mvt 2", "F Major", "Mozart", 7, 4, "Classical", ["sleepy"], "Piano Concerto No 21", 1],
["Piano Concerto No 21 Mvt 3", "C Major", "Mozart", 7, 4, "Classical", ["stamina"], "Piano Concerto No 21", 1],
["Piano Concerto No 23 Mvt 1", "A Major", "Mozart", 12, 3, "Classical", [], "Piano Concerto No 23", 1],
["Piano Concerto No 23 Mvt 2", "f# minor", "Mozart", 8, 3, "Classical", ["sad"], "Piano Concerto No 23", 1],
["Piano Concerto No 23 Mvt 3", "A Major", "Mozart", 9, 3, "Classical", ["stamina"], "Piano Concerto No 23", 1],
["Symphony No 40 Mvt 1", "g minor", "Mozart", 6, 5, "Classical", [], "", 1],
["Symphony No 40 Mvt 4", "g minor", "Mozart", 5, 5, "Classical", ["stamina"], "", 1],
["Symphony No 41 Mvt 1", "C Major", "Mozart", 8, 5, "Classical", ["stamina"], "", 1],
["Symphony No 41 Mvt 4", "C Major", "Mozart", 7, 5, "Classical", ["stamina"], "", 1],
["The Marriage of Figaro Overture", "D Major", "Mozart", 5, 4, "Classical", [], "", 1],
["Twelve Variations Ah vous diraisje maman", "C Major", "Mozart", 9, 4, "Classical", [], "", 1],
["Night on Bald Mountain", "d minor", "Mussorgsky", 10, 3, "Romantic", ["stamina"], "", 1],
["Une Larme", "g minor", "Mussorgsky", 5, 5, "Romantic", [], "", 1],
["Galop Infernal", "D Major", "Offenbach", 6, 4, "Romantic", [], "", 1],
["Caprice 24", "a minor", "Paganini", 5, 5, "Romantic", [], "", 1],
["La Campanella", "b minor", "Paganini", 5, 5, "Romantic", [], "", 1],
["Improvisation No 7", "C Major", "Poulenc", 3, 5, "Contemporary", [], "", 1],
["Improvisation No 15", "c minor", "Poulenc", 4, 4, "Contemporary", ["tender"], "", 1],
["Dance of the Knights", "e minor", "Prokofiev", 6, 5, "Contemporary", ["dark", "troll"], "", 1],
["Piano Concerto No 2 Mvt 1", "g minor", "Prokofiev", 12, 5, "Contemporary", [], "Piano Concerto No 2", 1],
["Piano Concerto No 2 Mvt 2", "d minor", "Prokofiev", 3, 5, "Contemporary", [], "Piano Concerto No 2", 1],
["Piano Concerto No 2 Mvt 3", "g minor", "Prokofiev", 8, 5, "Contemporary", [], "Piano Concerto No 2", 1],
["Piano Concerto No 2 Mvt 4", "G Major", "Prokofiev", 11, 5, "Contemporary", [], "Piano Concerto No 2", 1],
["Piano Concerto No 3 Mvt 1", "C Major", "Prokofiev", 9, 4, "Contemporary", [], "Piano Concerto No 3", 1],
["Piano Concerto No 3 Mvt 2", "a minor", "Prokofiev", 9, 5, "Contemporary", [], "Piano Concerto No 3", 1],
["Piano Concerto No 3 Mvt 3", "C Major", "Prokofiev", 10, 5, "Contemporary", [], "Piano Concerto No 3", 1],
["Sonata No 2", "d minor", "Prokofiev", 19, 3, "Contemporary", ["troll"], "", 1],
["Toccata Op 11", "d minor", "Prokofiev", 5, 5, "Contemporary", ["troll"], "", 1],
["Musettas Waltz", "E Major", "Puccini", 4, 4, "Romantic", [], "", 1],
["Barcarolle", "g minor", "Rachmaninoff", 8, 4, "Romantic", ["sad", "tender"], "", 1],
["Elegie Op 3 No 1", "eb minor", "Rachmaninoff", 6, 4, "Romantic", ["sleepy, impressions"], ["Morceaux de Fantaisie Op 3", 1], 1],
["Etude-Tableaux Op 33 No 1", "f minor", "Rachmaninoff", 3, 5, "Contemporary", [], "Eight Etude-Tableaux Op 33", 1],
["Etude-Tableaux Op 33 No 2", "C Major", "Rachmaninoff", 3, 5, "Contemporary", [], "Eight Etude-Tableaux Op 33", 1],
["Etude-Tableaux Op 33 No 3", "c minor", "Rachmaninoff", 6, 5, "Contemporary", [], "Eight Etude-Tableaux Op 33", 1],
["Etude-Tableaux Op 33 No 4", "d minor", "Rachmaninoff", 4, 5, "Contemporary", ["impressions"], "Eight Etude-Tableaux Op 33", 1],
["Etude-Tableaux Op 33 No 5", "eb minor", "Rachmaninoff", 2, 5, "Contemporary", ["impressions"], "Eight Etude-Tableaux Op 33", 1],
["Etude-Tableaux Op 33 No 6", "Eb Major", "Rachmaninoff", 2, 2, "Contemporary", ["stamina", "party"], "Eight Etude-Tableaux Op 33", 1],
["Etude-Tableaux Op 33 No 7", "g minor", "Rachmaninoff", 5, 4, "Contemporary", [], "Eight Etude-Tableaux Op 33", 1],
["Etude-Tableaux Op 33 No 8", "c# minor", "Rachmaninoff", 3, 5, "Contemporary", [], "Eight Etude-Tableaux Op 33", 1],
["Etude-Tableaux Op 39 No 1", "c minor", "Rachmaninoff", 3, 4, "Contemporary", ["impressions"], "", 1],
["Etude-Tableaux Op 39 No 2", "a minor", "Rachmaninoff", 7, 3, "Contemporary", ["impressions"], "", 1],
["Etude-Tableaux Op 39 No 3", "f# minor", "Rachmaninoff", 3, 5, "Contemporary", ["impressions"], "", 1],
["Etude-Tableaux Op 39 No 4", "b minor", "Rachmaninoff", 4, 5, "Contemporary", [], "", 1],
["Etude-Tableaux Op 39 No 5", "eb minor", "Rachmaninoff", 6, 5, "Contemporary", ["dark"], "", 1],
["Etude-Tableaux Op 39 No 8", "d minor", "Rachmaninoff", 4, 5, "Contemporary", ["impressions"], "", 1],
["Etude-Tableaux Op 39 No 9", "D Major", "Rachmaninoff", 4, 5, "Contemporary", ["impressions"], "", 1],
["How Fair This Spot Op 21 No 7", "A Major", "Rachmaninoff", 3, 4, "Romantic", ["tender"], "", 1],
["Italian Polka", "eb minor", "Rachmaninoff", 4, 3, "Romantic", ["dark"], "", 1],
["Lilacs Op 21 No 5", "Ab Major", "Rachmaninoff", 3, 1, "Romantic", ["sleepy", "impressions", "zen"], "", 2],
["Melody Op 3 No 3", "E Major", "Rachmaninoff", 5, 4, "Romantic", ["sleepy, impressions"], ["Morceaux de Fantaisie Op 3", 3], 1],
["Moments Musicaux Op 16 No 1", "bb minor", "Rachmaninoff", 7, 4, "Romantic", ["impressions"], "", 1],
["Moments Musicaux Op 16 No 4", "e minor", "Rachmaninoff", 4, 4, "Romantic", [], "", 1],
["Moments Musicaux Op 16 No 5", "Db Major", "Rachmaninoff", 4, 4, "Romantic", ["sleepy, impressions"], "", 1],
["Moments Musicaux Op 16 No 6", "C Major", "Rachmaninoff", 5, 5, "Romantic", [], "", 1],
["Morceaux de Salon Op 10 No 2", "A Major", "Rachmaninoff", 4, 4, "Contemporary", [], "", 1],
["Morceaux de Salon Op 10 No 5", "G Major", "Rachmaninoff", 4, 4, "Contemporary", [], "", 1],
["Morceaux de Salon Op 11 No 4", "A Major", "Rachmaninoff", 4, 4, "Contemporary", [], "", 1],
["Piano Concerto No 1 Mvt 1", "f# minor", "Rachmaninoff", 13, 4, "Romantic", ["legendary"], "Piano Concerto No 1", 1],
["Piano Concerto No 1 Mvt 2", "D Major", "Rachmaninoff", 7, 4, "Romantic", [], "Piano Concerto No 1", 1],
["Piano Concerto No 1 Mvt 3", "f# minor", "Rachmaninoff", 8, 4, "Romantic", [], "Piano Concerto No 1", 1],
["Piano Concerto No 2 Mvt 1", "c minor", "Rachmaninoff", 12, 1, "Romantic", ["dark", "legendary"], "Piano Concerto No 2", 2],
["Piano Concerto No 2 Mvt 2", "E Major", "Rachmaninoff", 13, 1, "Romantic", ["uplifting", "legendary"], "Piano Concerto No 2", 2],
["Piano Concerto No 2 Mvt 3", "c minor", "Rachmaninoff", 12, 3, "Romantic", [], "Piano Concerto No 2", 2],
["Piano Concerto No 3 Mvt 1", "d minor", "Rachmaninoff", 17, 3, "Romantic", [], "Piano Concerto No 3", 1],
["Piano Concerto No 3 Mvt 2", "d minor", "Rachmaninoff", 12, 4, "Romantic", [], "Piano Concerto No 3", 1],
["Piano Concerto No 3 Mvt 3", "d minor", "Rachmaninoff", 15, 4, "Romantic", ["stamina"], "Piano Concerto No 3", 1],
["Piano Sonata No 1 Mvt 12", "d minor", "Rachmaninoff", 19, 1, "Contemporary", ["legendary"], "Piano Sonatas", 1],
["Piano Sonata No 2", "bb minor", "Rachmaninoff", 23, 2, "Contemporary", ["legendary", "dark", "experimental"], "Piano Sonatas", 1],
["Polichinelle Op 3 No 4", "f# minor", "Rachmaninoff", 4, 4, "Romantic", ["impressions"], ["Morceaux de Fantaisie Op 3", 4], 1],
["Prelude Op 3 No 2", "c# minor", "Rachmaninoff", 4, 3, "Romantic", ["dark"], ["Morceaux de Fantaisie Op 3", 2], 1],
["Prelude Op 23 No 1", "f# minor", "Rachmaninoff", 4, 5, "Romantic", [], "", 1],
["Prelude Op 23 No 2", "Bb Major", "Rachmaninoff", 4, 3, "Romantic", ["stamina", "party"], "", 1],
["Prelude Op 23 No 4", "D Major", "Rachmaninoff", 6, 4, "Romantic", ["tender", "sleepy"], "", 1],
["Prelude Op 23 No 5", "g minor", "Rachmaninoff", 4, 4, "Romantic", ["stamina"], "", 1],
["Prelude Op 23 No 6", "Eb Major", "Rachmaninoff", 3, 4, "Romantic", ["tender", "sleepy"], "", 1],
["Prelude Op 23 No 7", "c minor", "Rachmaninoff", 4, 5, "Romantic", ["impressions"], "", 1],
["Prelude Op 23 No 10", "Gb Major", "Rachmaninoff", 4, 4, "Romantic", ["impressions", "tender", "sleepy"], "", 1],
["Prelude Op 32 No 5", "G Major", "Rachmaninoff", 4, 2, "Romantic", ["uplifting", "sleepy, impressions"], "", 1],
["Prelude Op 32 No 12", "g# minor", "Rachmaninoff", 3, 4, "Romantic", [], "", 1],
["Rhapsody on a Theme by Paganini", "a minor", "Rachmaninoff", 25, 3, "Contemporary", [], "", 1],
["Romance Op 17 No 3", "Ab Major", "Rachmaninoff", 8, 4, "Romantic", ["tender", "uplifting"], "", 1],
["Serenade Op 3 No 5", "bb minor", "Rachmaninoff", 4, 4, "Romantic", [], ["Morceaux de Fantaisie Op 3", 5], 1],
["Symphonic Dance Op 45 No 1", "c minor", "Rachmaninoff", 12, 4, "Romantic", [], "", 1],
["Symphony No 2 Mvt 1", "e minor", "Rachmaninoff", 21, 1, "Romantic", ["legendary"], "Symphony No 2", 1],
["Symphony No 2 Mvt 2", "a minor", "Rachmaninoff", 11, 1, "Romantic", ["legendary", "stamina"], "Symphony No 2", 1],
["Symphony No 2 Mvt 3", "A Major", "Rachmaninoff", 15, 1, "Romantic", ["legendary", "uplifting"], "Symphony No 2", 1],
["Symphony No 2 Mvt 4", "E Major", "Rachmaninoff", 15, 1, "Romantic", ["legendary", "stamina", "party"], "Symphony No 2", 1],
["Variations on a Theme by Chopin", "c minor", "Rachmaninoff", 27, 4, "Romantic", [], "", 1],
["Variations on a Theme by Corelli", "d minor", "Rachmaninoff", 19, 4, "Romantic", [], "", 1],
["Vocalise Op 34 No 14", "e minor", "Rachmaninoff", 8, 5, "Romantic", [], "", 1],
["Alborada del Gracioso", "", "Ravel", 7, 4, "Contemporary", [], ["Miroirs", 4], 1],
["Anime", "f# minor", "Ravel", 4, 5, "Contemporary", ["impressions"], ["Sonatine", 3], 1],
["Bolero", "C Major", "Ravel", 15, 4, "Contemporary", ["troll"], "", 1],
["Forlane", "e minor", "Ravel", 8, 5, "Contemporary", [], ["Le Tombeau de Couperin", 3], 1],
["Fugue", "e minor", "Ravel", 4, 5, "Contemporary", [], ["Le Tombeau de Couperin", 2], 1],
["Jeux deau", "E Major", "Ravel", 6, 5, "Contemporary", ["impressions"], "", 1],
["La Vallee des Cloches", "", "Ravel", 6, 4, "Contemporary", ["impressions"], ["Miroirs", 5], 1],
["Le Gibet", "eb minor", "Ravel", 7, 4, "Contemporary", ["impressions"], ["Gaspard de la Nuit", 2], 1],
["Menuet", "G Major", "Ravel", 5, 5, "Contemporary", [], ["Le Tombeau de Couperin", 5], 1],
["Modere", "f# minor", "Ravel", 5, 5, "Contemporary", ["impressions"], ["Sonatine", 1], 1],
["Mouvement de Menuet", "Db Major", "Ravel", 4, 5, "Contemporary", ["impressions"], ["Sonatine", 2], 1],
["Noctuelles", "", "Ravel", 5, 4, "Contemporary", ["impressions"], ["Miroirs", 1], 1],
["Oiseaux Tristes", "", "Ravel", 4, 5, "Contemporary", ["impressions"], ["Miroirs", 2], 1],
["Ondine", "C# Major", "Ravel", 7, 2, "Contemporary", ["impressions", "zen"], ["Gaspard de la Nuit", 1], 5],
["Pavane for Dead Princess", "G Major", "Ravel", 7, 5, "Contemporary", [], "", 1],
["Piano Concerto for the Left Hand", "D Major", "Ravel", 19, 5, "Contemporary", [], "", 1],
["Piano Concerto Mvt 1", "G Major", "Ravel", 9, 4, "Contemporary", ["troll"], "Piano Concerto", 1],
["Piano Concerto Mvt 2", "E Major", "Ravel", 10, 5, "Contemporary", ["troll"], "Piano Concerto", 1],
["Piano Concerto Mvt 3", "G Major", "Ravel", 4, 5, "Contemporary", ["troll"], "Piano Concerto", 1],
["Prelude", "G Major", "Ravel", 4, 4, "Contemporary", [], ["Le Tombeau de Couperin", 1], 1],
["Rigaudon", "C Major", "Ravel", 4, 5, "Contemporary", [], ["Le Tombeau de Couperin", 4], 1],
["Scarbo", "B Major", "Ravel", 9, 4, "Contemporary", ["impressions"], ["Gaspard de la Nuit", 3], 1],
["Toccata", "e minor", "Ravel", 5, 4, "Contemporary", [], ["Le Tombeau de Couperin", 6], 1],
["Une Barque sur la Ocean", "A Major", "Ravel", 7, 2, "Contemporary", ["impressions", "zen"], ["Miroirs", 3], 4],
["Intermezzo Serenata", "E Major", "Respighi", 3, 3, "Romantic", ["tender", "sleepy"], "", 1],
["Valse Caressante", "Eb Major", "Respighi", 4, 3, "Romantic", ["tender", "sleepy"], "", 1],
["Capriccio Espagnol", "A Major", "RimskyKorsakov", 16, 1, "Romantic", ["stamina"], "Capriccio Espagnol", 4],
["Flight of the Bumblebee", "a minor", "RimskyKorsakov", 1, 5, "Romantic", ["stamina", "troll"], "", 1],
["Procession of Nobles", "Eb Major", "RimskyKorsakov", 5, 5, "Romantic", [], "", 1],
["Barber of Seville", "E Major", "Rossini", 8, 4, "Romantic", [], "", 1],
["William Tell Overture Finale", "E Major", "Rossini", 4, 4, "Romantic", ["stamina"], "", 1],
["Aquarium", "a minor", "SaintSaens", 3, 4, "Romantic", ["sleepy, impressions"], "", 1],
["Aviary", "F Major", "SaintSaens", 2, 4, "Romantic", ["uplifting", "sleepy"], "", 1],
["Bacchanale from Samson and Delilah", "d minor", "SaintSaens", 8, 3, "Romantic", [], "", 1],
["Danse Macabre", "g minor", "SaintSaens", 8, 3, "Romantic", ["dark"], "", 1],
["Finale", "C Major", "SaintSaens", 2, 5, "Romantic", ["stamina"], "", 1],
["Introduction and Rondo Capriccioso Op 28", "a minor", "SaintSaens", 9, 5, "Romantic", ["sad"], "", 1],
["Piano Concerto No 2 Mvt 1", "g minor", "SaintSaens", 12, 3, "Romantic", [], "Piano Concerto No 2", 1],
["Piano Concerto No 2 Mvt 2", "Eb Major", "SaintSaens", 6, 3, "Romantic", [], "Piano Concerto No 2", 1],
["Piano Concerto No 2 Mvt 3", "g minor", "SaintSaens", 7, 3, "Romantic", ["dark", "stamina"], "Piano Concerto No 2", 1],
["Piano Concerto No 4 Mvt 1", "c minor", "SaintSaens", 13, 3, "Romantic", [], "Piano Concerto No 4", 1],
["Piano Concerto No 4 Mvt 2", "c minor", "SaintSaens", 14, 4, "Romantic", [], "Piano Concerto No 4", 1],
["Piano Concerto No 5 Mvt 1", "F Major", "SaintSaens", 10, 2, "Romantic", [], "Piano Concerto No 5", 1],
["Piano Concerto No 5 Mvt 2", "d minor", "SaintSaens", 11, 4, "Romantic", [], "Piano Concerto No 5", 1],
["Piano Concerto No 5 Mvt 3", "F Major", "SaintSaens", 6, 2, "Romantic", ["stamina", "party"], "Piano Concerto No 5", 1],
["Romance Op 67", "E Major", "SaintSaens", 8, 4, "Romantic", ["sleepy"], "", 1],
["Tarantella Op 6", "a minor", "SaintSaens", 8, 5, "Romantic", [], "", 1],
["The Swan", "G Major", "SaintSaens", 3, 3, "Romantic", ["tender", "sleepy"], "", 1],
["Turtles", "Bb Major", "SaintSaens", 2, 5, "Romantic", ["sleepy"], "", 1],
["Violin Concerto No 3 Mvt 1", "b minor", "SaintSaens", 10, 5, "Romantic", [], "", 1],
["Zapateado", "A Major", "Sarasate", 4, 4, "Romantic", ["stamina", "party"], "", 1],
["Gnossienne No 1", "f minor", "Satie", 4, 4, "Romantic", ["tender", "sleepy"], "", 1],
["Gymnopedie No 1", "D Major", "Satie", 4, 5, "Romantic", ["troll"], "", 1],
["Je te veux", "C Major", "Satie", 5, 4, "Romantic", [], "", 1],
["Humoresque", "Db Major", "Schedrin", 2, 5, "Contemporary", ["troll"], "", 1],
["Ave Maria", "Bb Major", "Schubert", 5, 3, "Romantic", ["tender", "sleepy"], "", 1],
["Erlkonig", "g minor", "Schubert", 5, 4, "Romantic", ["dark"], "", 1],
["Fantasia D 940", "f minor", "Schubert", 20, 4, "Romantic", [], "", 1],
["Impromptu Op 90 No 1", "c minor", "Schubert", 10, 3, "Romantic", ["sad"], "Four Impromptus Op 90", 1],
["Impromptu Op 90 No 2", "Eb Major", "Schubert", 5, 4, "Romantic", [], "Four Impromptus Op 90", 1],
["Impromptu Op 90 No 3", "Gb Major", "Schubert", 7, 4, "Romantic", ["sleepy"], "Four Impromptus Op 90", 1],
["Impromptu Op 90 No 4", "Ab Major", "Schubert", 7, 4, "Romantic", [], "Four Impromptus Op 90", 1],
["Impromptu Op 142 No 1", "f minor", "Schubert", 12, 5, "Romantic", [], "Four Impromptus Op 142", 1],
["Impromptu Op 142 No 2", "Ab Major", "Schubert", 8, 5, "Romantic", [], "Four Impromptus Op 142", 1],
["Impromptu Op 142 No 3", "Bb Major", "Schubert", 12, 4, "Romantic", ["tender", "sleepy"], "Four Impromptus Op 142", 1],
["Impromptu Op 142 No 4", "f minor", "Schubert", 6, 5, "Romantic", [], "Four Impromptus Op 142", 1],
["Piano Piece D 946 No 1", "eb minor", "Schubert", 15, 4, "Romantic", [], "Three Piano Pieces D 946", 1],
["Piano Piece D 946 No 2", "Eb Major", "Schubert", 14, 4, "Romantic", [], "Three Piano Pieces D 946", 1],
["Piano Piece D 946 No 3", "C Major", "Schubert", 7, 5, "Romantic", ["stamina"], "Three Piano Pieces D 946", 1],
["Piano Sonata D 664 Mvt 13", "A Major", "Schubert", 12, 3, "Romantic", [], "", 1],
["Piano Sonata D 894", "G Major", "Schubert", 40, 4, "Romantic", ["legendary"], "", 1],
["Piano Sonata D 958 Mvt 1", "c minor", "Schubert", 12, 4, "Romantic", ["legendary"], "The Last 3 Piano Sonatas", 1],
["Piano Sonata D 959 Mvt 14", "A Major", "Schubert", 30, 4, "Romantic", ["legendary"], "The Last 3 Piano Sonatas", 1],
["Piano Sonata D 960", "Bb Major", "Schubert", 42, 2, "Romantic", ["legendary"], "The Last 3 Piano Sonatas", 1],
["Serenade", "d minor", "Schubert", 4, 5, "Romantic", ["sad"], "", 1],
["Symphony No 5 Mvt 1", "Bb Major", "Schubert", 8, 4, "Romantic", [], "Symphony No 5", 1],
["Symphony No 5 Mvt 2", "Eb Major", "Schubert", 10, 4, "Romantic", [], "Symphony No 5", 1],
["Symphony No 5 Mvt 3", "g minor", "Schubert", 6, 4, "Romantic", [], "Symphony No 5", 1],
["Symphony No 5 Mvt 4", "Bb Major", "Schubert", 7, 4, "Romantic", [], "Symphony No 5", 1],
["Symphony No 8 Mvt 1", "b minor", "Schubert", 14, 3, "Romantic", [], "Symphony No 8", 1],
["Symphony No 8 Mvt 2", "E Major", "Schubert", 13, 4, "Romantic", [], "Symphony No 8", 1],
["Wanderer Fantasy Op 15", "C Major", "Schubert", 21, 4, "Romantic", ["legendary"], "", 1],
["Aufschwung Op 12 No 2", "f minor", "Schumann", 4, 5, "Romantic", [], "", 1],
["Dreaming Op 15 No 7", "F Major", "Schumann", 3, 5, "Romantic", ["sleepy"], "", 1],
["Des Abends Op 12 No 1", "Db Major", "Schumann", 4, 5, "Romantic", ["sleepy"], "", 1],
["Einfach Op 20 No 1", "Bb Major", "Schumann", 6, 5, "Romantic", [], "", 1],
["Eintritt", "Bb Major", "Schumann", 2, 5, "Romantic", [], "", 1],
["Freundliche Landschaft", "F Major", "Schumann", 2, 5, "Romantic", [], "", 1],
["In der Nacht Op 12 No 5", "f minor", "Schumann", 4, 5, "Romantic", ["dark"], "", 1],
["Of Foreign Lands and Peoples", "G Major", "Schumann", 2, 5, "Romantic", ["sleepy"], "", 1],
["Piano Concerto Op 54 Mvt 1", "a minor", "Schumann", 13, 4, "Romantic", [], "Piano Concerto Op 54", 1],
["Piano Concerto Op 54 Mvt 2", "F Major", "Schumann", 5, 4, "Romantic", [], "Piano Concerto Op 54", 1],
["Piano Concerto Op 54 Mvt 3", "A Major", "Schumann", 11, 4, "Romantic", [], "Piano Concerto Op 54", 1],
["Sonata No 1 Op 11", "f# minor", "Schumann", 30, 4, "Romantic", [], "", 1],
["Sonata No 2 Op 22", "g minor", "Schumann", 18, 3, "Romantic", ["dark", "legendary"], "", 1],
["Sonata No 3 Op 14 Mvt 1", "f minor", "Schumann", 8, 4, "Romantic", ["dark", "legendary"], "", 1],
["Vogel als Prophet", "g minor", "Schumann", 3, 4, "Romantic", [], "", 1],
["Widmung", "Ab Major", "Schumann", 4, 4, "Romantic", ["tender"], "", 1],
["Etude Op 8 No 12", "d# minor", "Scriabin", 3, 4, "Romantic", ["dark"], "", 1],
["Etude Op 42 No 5", "c# minor", "Scriabin", 3, 4, "Romantic", ["dark", "impressions"], "", 1],
["Fantasy Op 28", "b minor", "Scriabin", 10, 3, "Romantic", ["dark"], "", 1],
["Prelude Op 11 No 1", "C Major", "Scriabin", 1, 5, "Romantic", ["impressions"], "", 1],
["Prelude Op 11 No 8", "f# minor", "Scriabin", 2, 5, "Romantic", ["dark"], "", 1],
["Prelude Op 11 No 10", "c# minor", "Scriabin", 2, 5, "Romantic", [], "", 1],
["Sonata No 2", "g# minor", "Scriabin", 15, 3, "Romantic", ["experimental", "legendary"], "", 2],
["Dance from Dances of the Dolls", "D Major", "Shostakovich", 1, 5, "Contemporary", [], ["Dances of the Dolls", 7], 1],
["Dance No 1", "D Major", "Shostakovich", 3, 4, "Contemporary", [], ["Jazz Suite No 2", 2], 1],
["Dance No 2", "D Major", "Shostakovich", 4, 4, "Contemporary", [], ["Jazz Suite No 2", 3], 1],
["Finale", "F Major", "Shostakovich", 4, 4, "Contemporary", [], ["Jazz Suite No 2", 8], 1],
["Foxtrot", "f# minor", "Shostakovich", 3, 4, "Contemporary", [], ["Jazz Suite No 1", 3], 1],
["Gavotte", "C Major", "Shostakovich", 2, 5, "Contemporary", [], ["Dances of the Dolls", 2], 1],
["Hurdy Gurdy", "C Major", "Shostakovich", 1, 4, "Contemporary", [], ["Dances of the Dolls", 6], 1],
["Little Polka", "D Major", "Shostakovich", 3, 4, "Contemporary", [], ["Jazz Suite No 2", 4], 1],
["Lyric Waltz from Jazz Suite No 2", "c minor", "Shostakovich", 3, 4, "Contemporary", [], ["Jazz Suite No 2", 5], 1],
["Lyric Waltz from Dances of the Dolls", "F Major", "Shostakovich", 2, 4, "Contemporary", [], ["Dances of the Dolls", 1], 1],
["March", "F Major", 'Shostakovich', 3, 4, "Contemporary", [], ["Jazz Suite No 2", 1], 1],
["Piano Concerto No 1 Mvt 1", "c minor", "Shostakovich", 7, 4, "Contemporary", ["stamina"], "Piano Concerto No 1", 1],
["Piano Concerto No 1 Mvt 2", "e minor", "Shostakovich", 9, 5, "Contemporary", ["stamina"], "Piano Concerto No 1", 1],
["Piano Concerto No 1 Mvt 3", "Ab Major", "Shostakovich", 2, 5, "Contemporary", ["stamina"], "Piano Concerto No 1", 1],
["Piano Concerto No 1 Mvt 4", "c minor", "Shostakovich", 8, 5, "Contemporary", ["stamina"], "Piano Concerto No 1", 1],
["Piano Concerto No 2 Mvt 1", "F Major", "Shostakovich", 8, 3, "Contemporary", ["stamina"], "Piano Concerto No 2", 1],
["Piano Concerto No 2 Mvt 2", "c minor", "Shostakovich", 7, 2, "Contemporary", ["tender", "sleepy", "impressions"], "Piano Concerto No 2", 1],
["Piano Concerto No 2 Mvt 3", "F Major", "Shostakovich", 6, 3, "Contemporary", ["stamina"], "Piano Concerto No 2", 1],
["Polka from Dances of the Dolls", "a minor", "Shostakovich", 2, 5, "Contemporary", ["troll"], ["Dances of the Dolls", 4], 1],
["Polka from Jazz Suite No 1", "C Major", "Shostakovich", 3, 4, "Contemporary", [], ["Jazz Suite No 1", 2], 1],
["Polka from the Golden Age", "Bb Major", "Shostakovich", 3, 4, "Contemporary", ["troll"], "", 1],
["Romance", "F Major", "Shostakovich", 3, 5, "Contemporary", [], ["Dances of the Dolls", 3], 1],
["Waltz from Jazz Suite No 1", "g minor", "Shostakovich", 3, 5, "Contemporary", [], ["Jazz Suite No 1", 1], 1],
["Waltz No 1", "Bb Major", "Shostakovich", 4, 5, "Contemporary", [], ["Jazz Suite No 2", 6], 1],
["Waltz No 2", "c minor", "Shostakovich", 4, 4, "Contemporary", [], ["Jazz Suite No 2", 7], 1],
["Waltz Scherzo", "Eb Major", "Shostakovich", 3, 5, "Contemporary", [], ["Dances of the Dolls", 5], 1],
["Alla Marcia", "A Major", "Sibelius", 5, 3, "Romantic", [], ["Karelia Suite", 3], 1],
["Ballade", "a minor", "Sibelius", 9, 4, "Romantic", [], ["Karelia Suite", 2], 1],
["Interlude", "Eb Major", "Sibelius", 4, 2, "Romantic", [], ["Karelia Suite", 1], 1],
["The Spruce", "D Major", "Sibelius", 4, 4, "Romantic", [], "", 1],
["La Moldau", "e minor", "Smetana", 14, 4, "Romantic", [], "", 1],
["Blue Danube", "D Major", "Strauss", 10, 3, "Romantic", ["uplifting"], "", 1],
["Fledermaus Overture", "A Major", "Strauss", 9, 4, "Romantic", [], "", 1],
["Overture from Thus Spoke Zarathustra", "c minor", "Strauss", 2, 4, "Romantic", [], "", 1],
["Radtezky March", "D Major", "Strauss", 4, 4, "Romantic", [], "", 1],
["Tritsch Trasch Polka", "A Major", "Strauss", 3, 4, "Romantic", [], "", 1],
["Voices of Spring", "Bb Major", "Strauss", 6, 4, "Romantic", [], "", 1],
["Finale", "B Major", "Stravinsky", 4, 4, "Contemporary", [], ["The Firebird", 3], 1],
["Infernal Dance", "a minor", "Stravinsky", 6, 4, "Contemporary", [], ["The Firebird", 1], 1],
["Lullaby", "eb minor", "Stravinsky", 4, 4, "Contemporary", [], ["The Firebird", 2], 1],
["Russian Dance from Petrushka", "C Major", "Stravinsky", 3, 5, "Contemporary", [], "", 1],
["April Snowdrop", "Bb Major", "Tchaikovsky", 3, 4, "Romantic", [], ["The Seasons", 4], 1],
["Arabian Dance", "g minor", "Tchaikovsky", 4, 5, "Romantic", [], ["The Nutcracker Suite", 5], 1],
["August The Harvest", "b minor", "Tchaikovsky", 4, 5, "Romantic", [], ["The Seasons", 8], 1],
["Chinese Dance", "Bb Major", "Tchaikovsky", 1, 5, "Romantic", [], ["The Nutcracker Suite", 6], 1],
["Dance of the Little Swans", "f# minor", "Tchaikovsky", 2, 5, "Romantic", [], "", 1],
["Dance of the Mirlitons", "D Major", "Tchaikovsky", 3, 4, "Romantic", [], ["The Nutcracker Suite", 7], 1],
["Dance of the Suger Plum Fairy", "e minor", "Tchaikovsky", 2, 5, "Romantic", [], ["The Nutcracker Suite", 3], 1],
["December Christmas", "Ab Major", "Tchaikovsky", 5, 5, "Romantic", [], ["The Seasons", 12], 1],
["February The Carnival", "D Major", "Tchaikovsky", 3, 5, "Romantic", [], ["The Seasons", 2], 1],
["March Song of the Lark", "g minor", "Tchaikovsky", 3, 5, "Romantic", ["sad", "tender"], ["The Seasons", 3], 1],
["Marche", "G Major", "Tchaikovsky", 3, 5, "Romantic", ["stamina"], ["The Nutcracker Suite", 2], 1],
["Marche Slave", "bb minor", "Tchaikovsky", 10, 4, "Romantic", [], "", 1],
["May White Nights", "G Major", "Tchaikovsky", 5, 4, "Romantic", [], ["The Seasons", 5], 1],
["January At the Fireside", "A Major", "Tchaikovsky", 6, 5, "Romantic", [], ["The Seasons", 1], 1],
["July Reapers Song", "Eb Major", "Tchaikovsky", 2, 5, "Romantic", [], ["The Seasons", 7], 1],
["June Barcarolle", "g minor", "Tchaikovsky", 5, 5, "Romantic", ["sad", "tender"], ["The Seasons", 6], 1],
["November On the Troika", "E Major", "Tchaikovsky", 4, 5, "Romantic", [], ["The Seasons", 11], 1],
["October Autumn Song", "d minor", "Tchaikovsky", 7, 5, "Romantic", [], ["The Seasons", 10], 1],
["Overture from the Nutcracker Suite", "Bb Major", "Tchaikovsky", 4, 4, "Romantic", [], ["The Nutcracker Suite", 1], 1],
["Pas de Deux", "G Major", "Tchaikovsky", 6, 5, "Romantic", [], "", 1],
["Piano Concerto No 1 Mvt 1", "bb minor", "Tchaikovsky", 22, 4, "Romantic", [], "Piano Concerto No 1", 1],
["Piano Concerto No 1 Mvt 2", "Db Major", "Tchaikovsky", 8, 3, "Romantic", ["tender", "uplifting"], "Piano Concerto No 1", 1],
["Piano Concerto No 1 Mvt 3", "bb minor", "Tchaikovsky", 7, 4, "Romantic", ["dark", "stamina"], "Piano Concerto No 1", 1],
["September The Hunt", "G Major", "Tchaikovsky", 4, 5, "Romantic", [], ["The Seasons", 9], 1],
["Sleeping Beauty Waltz", "Bb Major", "Tchaikovsky", 5, 5, "Romantic", [], "", 1],
["Swan Lake Waltz", "A Major", "Tchaikovsky", 8, 5, "Romantic", [], "", 1],
["Swan Lake Theme", "b minor", "Tchaikovsky", 3, 4, "Romantic", [], "", 1],
["Sweet Dream Op 39 No 21", "C Major", "Tchaikovsky", 3, 4, "Romantic", ["tender", "sleepy", "uplifting"], "", 1],
["Trepak", "G Major", "Tchaikovsky", 2, 5, "Romantic", ["stamina"], ["The Nutcracker Suite", 4], 1],
["Valse Sentimentale Op 51 No 6", "f minor", "Tchaikovsky", 5, 5, "Romantic", ["sad"], "", 1],
["Waltz of the Flowers", "D Major", "Tchaikovsky", 7, 5, "Romantic", [], ["The Nutcracker Suite", 8], 1],
["Zapateado", "Db Major", "Turina", 5, 4, "Contemporary", [], "", 1],
["La Donna e Mobile", "Bb Major", "Verdi", 3, 5, "Romantic", [], "", 1],
["Ride of the Valkyries", "b minor", "Wagner", 5, 4, "Romantic", [], "", 1]];

/*
The metadata of each piece is stored in a list with the given format.
[piece name, key, composer, length (in minutes), rating (best = 1, worst = 5), era, playlists it belongs in, albums it belongs in]
albums it belongs in can either be a string or a list. if a list, stores [album name, index]. otherwise, indices are assumed to follow the default order given.
*/

//Build album map

const albumMap = new Map();
for (let i = 0; i < pieces.length; i++) {
    const data = pieces[i];
    const albumInfo = data[7];
    if (albumInfo === "") {
        continue;
    }

    const composer = data[2];
    const albumName = typeof albumInfo === "string" ? `${composer}: ${albumInfo}` : `${composer}: ${albumInfo[0]}`;
    if (!albumMap.has(albumName)) {
        albumMap.set(albumName, []);
    }

    const albumList = albumMap.get(albumName);
    if (typeof albumInfo === "string") {
        albumList.push([data[0], composer, data[3], i]);
    }
    else {
        const idx = albumInfo[1] - 1;
        albumList[idx] = [data[0], composer, data[3], i];
    }
}
const albumList = Array.from(albumMap.keys()).sort();